import Link from "next/link";
import { notFound } from "next/navigation";
import { CustomerShell } from "@/components/customer-shell";
import { MerchantOrderActions } from "@/components/merchant-order-actions";
import { getMerchantOrder } from "@/lib/merchant";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ orderId: string }> };
const statusLabel: Record<string, string> = { FINDING_STORE: "طلب جديد", STORE_CONFIRMING: "طلب جديد", ACCEPTED: "تم القبول", PREPARING: "قيد التجهيز", READY_FOR_PICKUP: "جاهز للاستلام", FAILED: "مرفوض" };

export default async function MerchantOrderPage({ params }: Props) {
  const { orderId } = await params; const { user, order } = await getMerchantOrder(orderId); if (!user || !order) notFound();
  const row = order as { id: string; status: string; payment_method: string; online_payment_method: string | null; subtotal: number; delivery_fee: number; service_fee: number; total: number; customer_note: string | null; delivery_address_snapshot: { label?: string; address_line: string; area: string; city: string }; stores: { name: string } | null; payments: { status: string }[] | null; order_items: { id: string; product_name_snapshot: string; unit_price: number; quantity: number; line_total: number }[]; created_at: string };
  const address = row.delivery_address_snapshot;
  return <CustomerShell><section className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-12"><Link href="/merchant" className="text-sm font-bold text-[#568171]">← كل الطلبات</Link><div className="mt-6 rounded-[2rem] bg-[#173b35] p-6 text-white"><p className="text-sm text-[#b7dec9]">{row.stores?.name || "المتجر"}</p><div className="mt-2 flex items-center justify-between gap-3"><h1 className="text-3xl font-black">#{row.id.slice(0, 8)}</h1><span className="rounded-full bg-white/15 px-3 py-1 text-sm font-bold">{statusLabel[row.status] || row.status}</span></div><p className="mt-3 text-sm text-[#d4e8df]">{new Date(row.created_at).toLocaleString("ar-EG")}</p></div><section className="mt-4 rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">المنتجات</h2>{row.order_items.map((item) => <div key={item.id} className="mt-4 flex justify-between gap-3 border-t border-[#edf2ee] pt-3"><span>{item.product_name_snapshot} × {item.quantity}</span><span className="font-black">{Number(item.line_total).toFixed(2)} ج.م</span></div>)}<div className="mt-5 space-y-2 border-t border-[#edf2ee] pt-4 text-sm"><div className="flex justify-between"><span>الإجمالي الفرعي</span><span>{Number(row.subtotal).toFixed(2)} ج.م</span></div><div className="flex justify-between"><span>التوصيل</span><span>{Number(row.delivery_fee).toFixed(2)} ج.م</span></div><div className="flex justify-between"><span>خدمة العميل</span><span>{Number(row.service_fee).toFixed(2)} ج.م</span></div><div className="flex justify-between pt-2 text-lg font-black"><span>الإجمالي</span><span>{Number(row.total).toFixed(2)} ج.م</span></div></div></section><div className="mt-4 grid gap-4 sm:grid-cols-2"><section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="font-black">الدفع</h2><p className="mt-2 text-sm text-[#6a8278]">{row.payment_method === "COD" ? "الدفع عند الاستلام" : `دفع إلكتروني (${row.online_payment_method || "غير محدد"})`}</p><p className="mt-1 text-sm font-bold text-[#27735e]">{row.payments?.[0]?.status === "CONFIRMED" ? "تم التأكيد" : "معلّق"}</p></section><section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="font-black">عنوان التوصيل</h2><p className="mt-2 text-sm leading-7 text-[#6a8278]">{address?.label && `${address.label} — `}{address?.address_line}، {address?.area}، {address?.city}</p></section></div>{row.customer_note && <section className="mt-4 rounded-3xl bg-[#fff8e8] p-5"><h2 className="font-black">ملاحظة العميل</h2><p className="mt-2 text-sm leading-7">{row.customer_note}</p></section>}<MerchantOrderActions orderId={row.id} status={row.status} /></section></CustomerShell>;
}
