import Link from "next/link";
import { CustomerShell } from "@/components/customer-shell";
import { getCustomerOrders } from "@/lib/orders";

export const dynamic = "force-dynamic";
const orderStatus: Record<string, string> = { CREATED: "تم إنشاء الطلب", PAYMENT_PENDING: "بانتظار الدفع", FINDING_STORE: "جارٍ البحث عن المتجر", STORE_CONFIRMING: "بانتظار تأكيد المتجر", WAITING_PAYMENT_CONFIRMATION: "بانتظار تأكيد الدفع", ACCEPTED: "تم قبول الطلب", PREPARING: "جارٍ التحضير", READY_FOR_PICKUP: "جاهز للاستلام", COURIER_ASSIGNED: "تم تعيين مندوب", COURIER_GOING_TO_STORE: "المندوب في طريقه للمتجر", COURIER_AT_STORE: "المندوب عند المتجر", PICKED_UP: "تم استلام الطلب", COURIER_GOING_TO_CUSTOMER: "الطلب في الطريق إليك", COURIER_AT_CUSTOMER: "المندوب وصل", CUSTOMER_CONFIRMED_DELIVERY: "تم تأكيد التسليم", DELIVERED: "تم التوصيل", CANCELLED: "ملغي", PAYMENT_FAILED: "فشل الدفع", PAYMENT_EXPIRED: "انتهت مهلة الدفع", FAILED: "تعذّر الطلب", REFUNDED: "تم رد المبلغ" };

export default async function OrdersPage() {
  const { user, orders } = await getCustomerOrders();
  return <CustomerShell><section className="shell-inner max-w-3xl px-3 py-7 sm:px-0 sm:py-10"><Link href="/account" className="text-sm font-bold text-[#568171]">← العودة إلى الحساب</Link><p className="section-kicker mt-6">سجل الشراء</p><h1 className="section-heading mt-1">طلباتي</h1>{!user ? <div className="surface-card mt-8 p-8 text-center"><p className="font-bold">سجّل الدخول لرؤية طلباتك.</p><Link href="/login" className="btn-primary mt-5 inline-flex">تسجيل الدخول</Link></div> : orders.length === 0 ? <div className="surface-card mt-8 border-dashed p-10 text-center"><p className="font-black">لا توجد طلبات بعد</p><Link href="/" className="mt-5 inline-flex font-bold text-[#27735e]">ابدأ التسوق</Link></div> : <div className="mt-8 space-y-3">{orders.map((order) => { const row = order as { id: string; total: number; status: string; payment_method: string; created_at: string; stores: { name: string } | null; payments: { status: string }[] | null }; const payment = row.payments?.[0]; return <Link key={row.id} href={`/orders/${row.id}`} className="surface-card block p-5 hover:-translate-y-0.5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-[#779187]">طلب #{row.id.slice(0, 8)}</p><h2 className="mt-1 text-lg font-black">{row.stores?.name || "متجر"}</h2></div><span className="status-chip bg-[#e6f2eb] text-[#27735e]">{orderStatus[row.status] || row.status}</span></div><div className="mt-4 flex flex-wrap justify-between gap-2 text-sm text-[#6a8278]"><span>{new Date(row.created_at).toLocaleDateString("ar-EG")} · {row.payment_method === "COD" ? "الدفع عند الاستلام" : "دفع إلكتروني"}</span><strong className="text-base text-[#173b35]">{Number(row.total).toFixed(2)} ج.م</strong></div><p className="mt-2 text-xs text-[#779187]">حالة الدفع: {payment?.status === "CONFIRMED" ? "تم التأكيد" : "معلّق"}</p></Link>; })}</div>}</section></CustomerShell>;
}
