import Link from "next/link";
import { CustomerShell } from "@/components/customer-shell";
import { MerchantRefresh } from "@/components/merchant-refresh";
import { getMerchantOrders } from "@/lib/merchant";

export const dynamic = "force-dynamic";
const statusLabel: Record<string, string> = { FINDING_STORE: "طلبات جديدة", STORE_CONFIRMING: "طلبات جديدة", ACCEPTED: "مقبولة", PREPARING: "قيد التجهيز", READY_FOR_PICKUP: "جاهزة للاستلام", FAILED: "مرفوضة" };

export default async function MerchantDashboard() {
  const { user, stores, orders } = await getMerchantOrders();
  const grouped = ["FINDING_STORE", "STORE_CONFIRMING", "ACCEPTED", "PREPARING", "READY_FOR_PICKUP"].map((status) => ({ status, orders: orders.filter((order) => (order as { status: string }).status === status) }));
  return <CustomerShell><section className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-[#779187]">مساحة التاجر</p><h1 className="mt-1 text-3xl font-black">طلبات المتجر</h1><p className="mt-2 text-sm text-[#6a8278]">تابع الطلبات وانتقل بها من القبول إلى الجاهزية.</p></div>{user && <div className="flex items-center gap-3 text-sm text-[#6a8278]"><MerchantRefresh />{stores.map((store) => <span key={store.id} className="mr-2 rounded-full bg-[#e6f2eb] px-3 py-1 font-bold text-[#27735e]">{store.name}</span>)}</div>}</div>{!user ? <div className="mt-8 rounded-3xl bg-white p-8 text-center"><p className="font-bold">سجّل الدخول للوصول إلى مساحة التاجر.</p><Link href="/login?next=/merchant" className="mt-5 inline-flex rounded-2xl bg-[#173b35] px-5 py-3 font-black text-white">تسجيل الدخول</Link></div> : stores.length === 0 ? <div className="mt-8 rounded-3xl border border-dashed border-[#c8dcd1] p-10 text-center"><p className="font-black">لا يوجد متجر مرتبط بهذا الحساب.</p><p className="mt-2 text-sm text-[#6a8278]">يجب أن يربط المسؤول حسابك بمتجر ودور MERCHANT.</p></div> : <div className="mt-8 grid gap-6 lg:grid-cols-3">{grouped.map((group) => <section key={group.status} className="rounded-3xl bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black">{statusLabel[group.status]}</h2><span className="rounded-full bg-[#faf8f3] px-3 py-1 text-xs font-black">{group.orders.length}</span></div>{group.orders.length === 0 ? <p className="rounded-2xl bg-[#faf8f3] p-5 text-center text-sm text-[#6a8278]">لا توجد طلبات</p> : <div className="space-y-3">{group.orders.map((order) => { const row = order as { id: string; total: number; payment_method: string; created_at: string; stores: { name: string } | null; order_items: unknown[] }; return <Link key={row.id} href={`/merchant/orders/${row.id}`} className="block rounded-2xl border border-[#e1ebe5] p-4 transition hover:shadow-md"><div className="flex justify-between gap-3"><p className="text-xs text-[#779187]">#{row.id.slice(0, 8)}</p><p className="text-xs text-[#779187]">{new Date(row.created_at).toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" })}</p></div><h3 className="mt-2 font-black">{row.stores?.name || "المتجر"}</h3><div className="mt-3 flex justify-between text-sm"><span>{row.order_items.length} منتجات · {row.payment_method === "COD" ? "استلام نقدي" : "دفع إلكتروني"}</span><strong>{Number(row.total).toFixed(2)} ج.م</strong></div></Link>; })}</div>}</section>)}</div>}</section></CustomerShell>;
}
