"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AdminCourierApplication, AdminMerchantApplication } from "@/lib/admin";

function ActionButtons({ kind, id, onDone }: { kind: "merchant" | "courier"; id: string; onDone: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [rejecting, setRejecting] = useState(false); const [note, setNote] = useState("");
  async function run(action: string) { setBusy(true); setError(null); const response = await fetch("/api/admin/applications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, id, reviewNote: note }) }); const body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error ?? "تعذّر تنفيذ الإجراء"); else onDone(); setBusy(false); }
  return <div className="mt-4 flex flex-wrap gap-2">{rejecting && <input value={note} onChange={(event) => setNote(event.target.value)} placeholder="ملاحظة للمتقدم (اختياري)" maxLength={500} className="min-h-11 w-full rounded-lg border border-[#e7e5e4] px-3 text-sm sm:w-64" />}{!rejecting ? <><button disabled={busy} onClick={() => void run(`approve-${kind}`)} className="btn-primary min-h-11 px-4 py-2 text-sm">{busy ? "جارٍ…" : "اعتماد"}</button><button disabled={busy} onClick={() => setRejecting(true)} className="rounded-lg border border-[#f0b3a8] px-4 py-2 text-sm font-black text-[#a52511]">رفض</button></> : <><button disabled={busy} onClick={() => void run(`reject-${kind}`)} className="rounded-lg bg-[#b51d04] px-4 py-2 text-sm font-black text-white">تأكيد الرفض</button><button disabled={busy} onClick={() => setRejecting(false)} className="btn-secondary min-h-11 px-4 py-2 text-sm">إلغاء</button></>}{error && <p role="alert" className="w-full text-xs font-bold text-[#ba1a1a]">{error}</p>}</div>;
}

export function AdminApplicationList({ merchants, couriers }: { merchants: AdminMerchantApplication[]; couriers: AdminCourierApplication[] }) {
  const router = useRouter();
  const pendingMerchants = merchants.filter((item) => item.status === "PENDING"); const pendingCouriers = couriers.filter((item) => item.verification_status === "PENDING_VERIFICATION");
  return <div className="space-y-8"><section><div className="mb-4 flex items-center justify-between"><div><p className="section-kicker">تحتاج إلى مراجعة</p><h2 className="section-heading mt-1">طلبات المتاجر</h2></div><span className="status-chip bg-[#fff7ed] text-[#895100]">{pendingMerchants.length} قيد المراجعة</span></div>{pendingMerchants.length === 0 ? <div className="surface-card border-dashed p-8 text-center text-sm text-[#57534e]">لا توجد طلبات متاجر معلقة.</div> : <div className="grid gap-3 lg:grid-cols-2">{pendingMerchants.map((item) => <article key={item.id} className="surface-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-black">{item.store_name}</h3><p className="mt-1 text-sm text-[#57534e]">{item.full_name}</p></div><span className="status-chip bg-[#fff7ed] text-[#895100]">قيد المراجعة</span></div><dl className="mt-4 grid gap-2 text-sm text-[#57534e] sm:grid-cols-2"><div><dt className="text-xs text-[#907069]">الهاتف</dt><dd className="font-bold">{item.phone}</dd></div><div><dt className="text-xs text-[#907069]">تاريخ الطلب</dt><dd className="font-bold">{new Date(item.created_at).toLocaleDateString("ar-EG")}</dd></div></dl><ActionButtons kind="merchant" id={item.id} onDone={() => router.refresh()} /></article>)}</div>}</section><section><div className="mb-4 flex items-center justify-between"><div><p className="section-kicker">التحقق</p><h2 className="section-heading mt-1">طلبات المندوبين</h2></div><span className="status-chip bg-[#fff7ed] text-[#895100]">{pendingCouriers.length} قيد التحقق</span></div>{pendingCouriers.length === 0 ? <div className="surface-card border-dashed p-8 text-center text-sm text-[#57534e]">لا توجد طلبات مندوبين معلقة.</div> : <div className="grid gap-3 lg:grid-cols-2">{pendingCouriers.map((item) => <article key={item.id} className="surface-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-black">{item.full_name || "مندوب"}</h3><p className="mt-1 text-sm text-[#57534e]">{item.phone || "بدون هاتف"}</p></div><span className="status-chip bg-[#fff7ed] text-[#895100]">قيد التحقق</span></div><dl className="mt-4 grid gap-2 text-sm text-[#57534e] sm:grid-cols-2"><div><dt className="text-xs text-[#907069]">المركبة</dt><dd className="font-bold">{item.vehicle_type || "غير محدد"}</dd></div><div><dt className="text-xs text-[#907069]">اللوحة</dt><dd className="font-bold">{item.vehicle_plate || "غير محددة"}</dd></div></dl><ActionButtons kind="courier" id={item.id} onDone={() => router.refresh()} /></article>)}</div>}</section></div>;
}
