import Link from "next/link";

type Props = { kind: "merchant" | "courier"; status: "pending" | "rejected"; title?: string };
const content = { merchant: { pending: "طلب تسجيل متجرك قيد المراجعة", rejected: "لم تتم الموافقة على طلب المتجر", pendingBody: "راجع فريق هاتها بيانات المتجر. ستتمكن من إدارة المنتجات والطلبات بعد الاعتماد.", rejectedBody: "يمكنك مراجعة البيانات وإرسال طلب جديد بالمعلومات المحدثة.", action: "مراجعة بيانات المتجر", href: "/register/merchant", steps: ["تم إرسال الطلب", "قيد المراجعة", "تم الاعتماد", "المتجر جاهز"] }, courier: { pending: "طلب انضمامك كمندوب قيد التحقق", rejected: "لم تتم الموافقة على طلب المندوب", pendingBody: "يتحقق فريق هاتها من بياناتك. ستظهر مهام التوصيل بعد اعتماد الحساب.", rejectedBody: "يمكنك مراجعة بيانات التحقق وإرسال طلب جديد عند توفر معلومات محدثة.", action: "إرسال طلب جديد", href: "/register/courier", steps: ["تم إرسال الطلب", "قيد التحقق", "تم الاعتماد", "جاهز للتوصيل"] } } as const;

export function OnboardingStatusCard({ kind, status }: Props) {
  const item = content[kind]; const pending = status === "pending";
  return <section className="surface-card mx-auto max-w-2xl p-5 sm:p-8"><div className="flex items-start gap-4"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-lg text-xl font-black ${pending ? "bg-[#fff7ed] text-[#895100]" : "bg-[#fdf2f0] text-[#b51d04]"}`}>{pending ? "…" : "!"}</div><div><p className="section-kicker">{kind === "merchant" ? "مسار المتجر" : "مسار التوصيل"}</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{pending ? item.pending : item.rejected}</h1><p className="mt-3 text-sm leading-7 text-[#57534e]">{pending ? item.pendingBody : item.rejectedBody}</p></div></div><ol className="mt-8 grid gap-3 sm:grid-cols-4">{item.steps.map((step, index) => { const active = pending ? index < 2 : index === 1; return <li key={step} className={`rounded-lg border p-3 text-center text-xs font-black ${active ? "border-[#fd9d1a] bg-[#fff7ed] text-[#663b00]" : index === 0 && !pending ? "border-[#e4beb6] bg-[#fdf2f0] text-[#b51d04]" : "border-[#e7e5e4] bg-white text-[#907069]"}`}><span className="mx-auto mb-2 grid h-7 w-7 place-items-center rounded-full bg-current/10">{index + 1}</span>{step}</li>; })}</ol><div className="mt-8 flex flex-wrap gap-3"><Link href={pending ? "/" : item.href} className="btn-primary">{pending ? "العودة إلى الرئيسية" : item.action}</Link><Link href="/account" className="btn-secondary">الحساب</Link></div></section>;
}
