"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { CourierApplicationInput, MerchantApplicationInput, OnboardingRole } from "@/lib/onboarding";

export function RegistrationForm({ role }: { role: OnboardingRole }) {
  const router = useRouter(); const [form, setForm] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const set = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const field = (key: string, label: string, type = "text", required = true) => <label className="block text-sm font-bold">{label}<input required={required} type={type} value={form[key] ?? ""} onChange={set(key)} className="mt-1 w-full rounded-2xl border border-[#c8dcd1] px-4 py-3" /></label>;
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(null); setMessage(null); const auth = createClient(); const base = { full_name: form.fullName, phone: form.phone, onboarding_role: role }; let storeLocation: Record<string, unknown> | null = null; if (role === "MERCHANT" && form.storeLocation?.trim()) { try { storeLocation = JSON.parse(form.storeLocation) as Record<string, unknown>; } catch { setError("إحداثيات المتجر يجب أن تكون JSON صحيحة."); setLoading(false); return; } } const metadata = role === "MERCHANT" ? { ...base, merchant_application: { fullName: form.fullName, phone: form.phone, email: form.email, storeName: form.storeName, storeCategory: form.storeCategory, storeAddress: form.storeAddress, storePhone: form.storePhone, storeLocation, businessDescription: form.businessDescription } satisfies Partial<MerchantApplicationInput> } : role === "COURIER" ? { ...base, courier_application: { fullName: form.fullName, phone: form.phone, email: form.email, nationalIdReference: form.nationalIdReference, vehicleType: form.vehicleType, vehiclePlate: form.vehiclePlate } satisfies Partial<CourierApplicationInput> } : base; const { data, error: authError } = await auth.auth.signUp({ email: form.email, password: form.password, options: { data: metadata, emailRedirectTo: `${window.location.origin}/auth/callback` } }); if (authError) { setError(authError.message); setLoading(false); return; } if (data.session) { const bootstrapResponse = await fetch("/api/onboarding/bootstrap", { method: "POST" }); if (!bootstrapResponse.ok) { setError(role === "MERCHANT" ? "تعذّر تسجيل طلب المتجر. حاول تسجيل الدخول مرة أخرى." : "تعذّر إكمال إعداد الحساب. حاول تسجيل الدخول مرة أخرى."); setLoading(false); return; } const response = await fetch("/api/onboarding/next", { cache: "no-store" }); const body = await response.json().catch(() => ({})); router.push(typeof body.path === "string" ? body.path : "/"); router.refresh(); } else setMessage(role === "MERCHANT" ? "تم إنشاء الحساب. راجع بريدك الإلكتروني لتأكيد الحساب، وبعد التأكيد سيُسجّل طلب المتجر للمراجعة." : "تم إنشاء الحساب. راجع بريدك الإلكتروني لتأكيد الحساب، ثم سجّل الدخول للمتابعة."); setLoading(false); }
  const title = role === "CUSTOMER" ? "إنشاء حساب عميل" : role === "MERCHANT" ? "طلب تسجيل متجر" : "طلب تسجيل مندوب";
  return <main className="shell-inner max-w-2xl px-3 py-8 sm:px-0 sm:py-12"><div className="surface-card p-5 sm:p-8"><p className="section-kicker">إنشاء حساب</p><h1 className="section-heading mt-2">{title}</h1><p className="mt-3 text-sm leading-7 text-[#6a8278]">سيتم استخدام هوية Supabase واحدة، ولن يتم منح صلاحيات التاجر أو المندوب قبل اعتمادها.</p><form onSubmit={submit} className="mt-7 space-y-4">{field("fullName", "الاسم الكامل")}{field("phone", "رقم الهاتف", "tel")}{field("email", "البريد الإلكتروني", "email")}{role === "MERCHANT" && <fieldset className="space-y-4 rounded-2xl bg-[#f5faf7] p-4"><legend className="px-1 text-sm font-black">بيانات المتجر</legend>{field("storeName", "اسم المتجر")}{field("storeCategory", "تصنيف المتجر")}{field("storeAddress", "عنوان المتجر")}{field("storePhone", "هاتف المتجر", "tel")}{field("businessDescription", "وصف المتجر (اختياري)", "text", false)}<label className="block text-sm font-bold">إحداثيات المتجر (اختياري)<textarea value={form.storeLocation ?? ""} onChange={set("storeLocation")} placeholder='{"lat": 31.0, "lng": 31.0}' className="mt-1 min-h-20 w-full rounded-2xl border border-[#c8dcd1] px-4 py-3" /></label></fieldset>}{role === "COURIER" && <fieldset className="space-y-4 rounded-2xl bg-[#f5faf7] p-4"><legend className="px-1 text-sm font-black">بيانات التحقق والتوصيل</legend>{field("nationalIdReference", "مرجع بيانات الهوية")}{field("vehicleType", "نوع المركبة")}{field("vehiclePlate", "رقم اللوحة")}</fieldset>}{field("password", "كلمة المرور", "password")}<button disabled={loading} className="btn-primary w-full disabled:opacity-60">{loading ? "جارٍ إنشاء الحساب…" : "إنشاء الحساب"}</button></form>{message && <p className="mt-4 rounded-2xl bg-[#e2f1e9] p-4 text-sm font-bold text-[#27735e]">{message}</p>}{error && <p role="alert" className="mt-4 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</p>}<p className="mt-6 text-center text-sm text-[#6a8278]">لديك حساب؟ <Link href="/login" className="font-black text-[#173b35] underline">تسجيل الدخول</Link></p></div></main>;
}
