"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { FavoriteButton } from "@/components/favorite-button";
import { inventoryLabel } from "@/lib/inventory";
import type { StoreProduct } from "@/lib/customer";

export function StoreProductGrid({ storeId, products }: { storeId: string; products: StoreProduct[] }) {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("all");
  const categories = useMemo(() => Array.from(new Set(products.map((item) => item.product?.category).filter((value): value is string => Boolean(value)))), [products]);
  const filtered = products.filter((item) => { const matchesSearch = !search.trim() || `${item.product?.name ?? ""} ${item.product?.description ?? ""}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()); const matchesCategory = category === "all" || item.product?.category === category; return matchesSearch && matchesCategory; });
  return <div><div className="mb-5 grid gap-3 sm:grid-cols-[1fr_auto]"><label className="sr-only" htmlFor="product-search">البحث في منتجات المتجر</label><div className="flex min-h-12 items-center rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4"><span aria-hidden="true" className="ml-3 text-lg text-[var(--muted-soft)]">⌕</span><input id="product-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث داخل المنتجات…" className="min-w-0 flex-1 border-0 bg-transparent px-0 outline-none" /></div>{categories.length > 0 && <select value={category} onChange={(event) => setCategory(event.target.value)} className="min-h-12 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 font-bold"><option value="all">كل التصنيفات</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select>}</div>{filtered.length === 0 ? <div className="empty-state">لا توجد منتجات مطابقة للبحث.</div> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => { const available = item.is_active && item.inventory?.status === "AVAILABLE"; const availability = inventoryLabel(item.inventory?.status ?? "UNKNOWN"); const card = <article className={`surface-card relative p-4 ${available ? "transition hover:-translate-y-0.5" : "opacity-65"}`}><div className="absolute left-4 top-4 z-10"><FavoriteButton storeProductId={item.id} /></div><div className="flex h-32 items-center justify-center rounded-xl bg-[var(--surface-muted)] text-5xl font-black text-[var(--brand)]">{item.product?.name.trim().charAt(0) || "؟"}</div><div className="mt-4 flex items-start justify-between gap-3"><div><h3 className="text-lg font-black">{item.product?.name || "منتج"}</h3>{item.product?.category && <p className="mt-1 text-xs font-bold text-[var(--muted-soft)]">{item.product.category}</p>}</div><span className="whitespace-nowrap text-lg font-black text-[var(--brand)]">{item.effective_price < Number(item.price) && <del className="ml-1 text-sm text-[var(--muted-soft)]">{Number(item.price).toFixed(2)}</del>}{Number(item.effective_price).toFixed(2)} ج.م</span></div>{item.offers.length > 0 && <p className="mt-2 text-xs font-black text-[var(--warning)]">{item.offers[0].name}</p>}<p className="mt-2 line-clamp-2 text-sm leading-6 text-[var(--muted)]">{item.product?.description || "تفاصيل المنتج غير متاحة"}</p><span className={`status-chip mt-4 ${availability.className}`}>{available ? availability.text : "غير متاح للطلب"}</span></article>; return available ? <Link key={item.id} href={`/stores/${storeId}/products/${item.id}`}>{card}</Link> : <div key={item.id}>{card}</div>; })}</div>}</div>;
}
